### ISSUE TITLE
Jape hanging on proof load

### ISSUE THREAD

**Issue by haz** [RBornat/jape#20] opened 2022-12-14 17:34 UTC
Seeing some odd behaviour on a particular set of proofs a student has submitted. Steps to reproduce with the latest Jape (tested on Windows)

1. Fire up Jape.
2. Load the natural deduction theory (vanilla from the provided `examples/` folder).
3. Load the attached [proof.jp.txt](https://github.com/RBornat/jape/files/10230286/proof.jp.txt) file (added .txt to be allow for upload here).

This is what I'm seeing in the console, and Jape seems to be working away at something in a never-ending loop:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/225019/207666308-2415b43a-828c-4a7b-8957-5d0c787a1df4.png)

**Comment by RBornat** [comment] 2022-12-14 18:14
I'm not very well at present. I shall look at this problem as soon as I can.

Richard

**Comment by haz** [comment] 2022-12-14 18:18
Really sorry to hear, @RBornat ! Not rush at all -- we were able to move forward without loading. Just found it an odd behaviour (first time seeing it through hundreds of students).

Hope you feel well soon!

**Comment by RBornat** [comment] 2023-02-16 15:24
Long comment.

I found a bug and a feature. The bug is fixed in jape 9.1.5, but it may never bite you if you stick with an earlier release. The feature, which I haven't yet managed to dent, stops this particular theorem loading.

Ok, the bug. Jape deals with predicate formulas like P(i) by making them, in rules, into substitutions. Something like _P[x\\i], where it invents a fresh name x. Then it ought to unify _P with P(x) and then the substitution turns that into P(i). That's the short explanation. Either jape wasn't doing that, or it was doing it too late. At any rate it now does it in a way that seems to be the right way. 

But the bug wasn't, I think, the real problem. The first theorem in the list had 23 antecedents, and most of them unify with each other. When jape loads a proof it tries to see if it's a proof of the theorem that it already knew about. In this case it ought not to to do that, because it's the first time it's seen the theorem but (bug? yes, I suppose) it tries to unify it with itself. If it actually managed to do that, it would generate some large factorial number of ways of matching, and then ignore them. I think it never gets to that point, but so far I haven't proved that.

The fact is that if jape ever approved your theorem it would be a useless theorem. All those As and Bs and Cs and Ps aren't constants, they are unknowns capable of unifying with other unknowns. Ditto all the other elements, even the variables x0, x1, and so on. If you tried to apply the theorem during a proof, jape would (in principle) find all the myriad ways in which the theorem might apply and ask you to choose between them. That wouldn't be possible: the GUI mechanism we have for that choice would run out of window space, amongst other things. *That*'s the feature.

So, the proof still doesn't load in 9.1.5, and if I get round to chasing the reason again I may be able to be more definite about the cause. But if I'm right it would be a useless theorem anyway. The odd thing is that the proof is so easy ... that's the feature, probably.

Version 9.1.5 should be online a few minutes after the time you read this comment.

**Comment by haz** [comment] 2023-02-16 17:47
Brilliant, thank you @RBornat !

So the heritage of this is that students are coming up with a logical encoding for a setting of their choice (e.g., solving sudoku with propositional logic), and part of their project grade is to prove a theorem on a simplified version of their setting (e.g., a 2x2 sudoku that demonstrates one position has only a single value remaining).

We don't expect to ever load these theorems and apply them in a proof, but would like to at least allow the students to save their proof and share it with us. We can lean on just having them screenshot things for now, but a way to load a proof that avoids the "this is too big feature" would be ideal.

It's actually a very common pattern for us teaching the course -- we don't need to apply their theorems, but rather just load their jape files to see if they've proven the sequents we've assigned for assignments/quizzes.

Anyways, thanks again for hunting down this finicky corner case!

**Comment by RBornat** [comment] 2023-03-09 14:56
I've been distracted for a while: first by poor health, then by problems issuing a release of my quantum calculator (github.com/mdxtoc/qtpi). All partly solved now.

So I thought I'd come back to this problem. To my *great*surprise, I found that I had substantially fixed the problem. That is, on my lovely fast M1 Mac Mini, it loaded proof.jp in 35 CPU seconds. I'd been chasing the cause of the slow load for so long, with tons of debugging flags turned on, that I hadn't bothered to see if version 9.1.5 was capable!

So, my previous denials are no longer operative (or whatever it was that Dick Cheney said). It's fixed. *But, but, but* that load is still slow, and I think I can see a pretty obvious way to speed it up, so watch this space.

Mind you, the theorems are still useless.

**Comment by RBornat** [comment] 2023-03-15 18:07
OK, all fixed. 9.1.6a (listed under 9.1.6 because the a doesn't mean anything).

Thanks for prompting me; thanks for waiting so long while I slowly got it right (I hope).

**Closed by RBornat** 2023-03-15 18:07 UTC
